### ISSUE TITLE
Database schema

### ISSUE THREAD

**Issue by ragarwa7** [ragarwa7/WolfPal#2]
- List of tables and relevant fields.
- Relationship 
- ER Diagram

**Comment by mohitsat** [comment]
Beginning work today, 02/09/2018
Target ER diagram

**Comment by mohitsat** [comment]
Completed ER diagram, 02/09/2018
Next target, DB schema.

**Comment by ragarwa7** [comment]
We need to make below changes:
1. Start time and End time in table schedule instead of time.
2. Student number limit in the schedule table.
3. We may need a new table to store average grades.

**Comment by mohitsat** [comment]
Completed yesterday
