### ISSUE TITLE
Grade and workload backend logic

### ISSUE THREAD

**Issue by mohitsat** [ragarwa7/WolfPal#8]
Average grade business logic needs to be planned.
Bot can ask user specific questions to evaluate the workload a certain student can handle.
We can get information whether to suggest a project based, an exam based, or maybe a theoretical subject by getting this information.
We can give the student a weight limit based on it. 
We can then suggest workload less than that limit.

**Comment by WYYinGH** [comment]
Partial Done. Please see issue #9

**Comment by mohitsat** [comment]
Completed
